baseurl = "http://www.shaneword.com"
languageCode = "en-us"
publishdir = "../../build"
title = "Shane Word"
uglyurls = true
googleAnalytics = "UA-83865818-1"

[permalinks]
  post = "/post/:year/:month/:day/:filename"

[params]
  useRSS = false
  author = "Shane Word"
  description = "Where do we go from here?"
